version: '3.8'

services:
  vct-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vct-dashboard
    ports:
      - "8501:8501"
    volumes:
      # Persist the SQLite database
      - vct_data:/app/vct.db
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=vct-dashboard"
      - "description=VCT Dashboard - VALORANT Champions Tour Analytics"

  # Optional: Add a database management interface
  adminer:
    image: adminer:latest
    container_name: vct-adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite:///app/vct.db
    volumes:
      - vct_data:/app/vct.db:ro
    restart: unless-stopped
    profiles:
      - admin
    labels:
      - "description=Database administration interface for VCT database"

volumes:
  vct_data:
    driver: local
    name: vct_dashboard_data

networks:
  default:
    name: vct-dashboard-network
